name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
    - main
    tags:
    - v*
    
# on: push    # Default will running for every branch.
    
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: macos-latest
    steps:
    
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.1'
        channel: 'stable'
    
    # Get flutter dependencies.
    - name: Get flutter dependencies
      run: flutter pub get
      working-directory: ./apps/auth-challenge-zog/

    # Run widget tests for flutter project.
    - run: flutter test test/authentication_test.dart
      working-directory: ./apps/auth-challenge-zog/

    # Build apk.
    - name: Build Android App
      if: startsWith(github.ref, 'refs/tags/v')
      run: flutter build apk
      working-directory: ./apps/auth-challenge-zog/
    
    - name: Build iOS App
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      working-directory: ./apps/auth-challenge-zog/
    
    # Upload generated apk to the artifacts.
    - name: Release Apps
      if: startsWith(github.ref, 'refs/tags/v')
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        artifacts: 'build/app/outputs/**/*.apk,build/ios/iphoneos/app.ipa'
